##
## author: Karol Tomczuk <karol.tomczuk@zerodowntime.pl>
##

---
- vsphere_guest:
    vcenter_hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vmname }}"
    state: powered_on
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd:  yes
      notes: This is a test VM
      folder: MyFolder
    vm_disk:
      disk1:
        size_gb: 10
        type: thin
        datastore: "{{ storagename}}"
        # VMs can be put into folders. The value given here is either the full path
        # to the folder (e.g. production/customerA/lamp) or just the last component
        # of the path (e.g. lamp):
        folder: production/customerA/lamp
    vm_nic:
      nic1:
        type: vmxnet3
        network: "{{ networkname1 }}"
        network_type: "{{ networktype1 }}"
      nic2:
        type: vmxnet3
        network: "{{ networkname2 }}"
        network_type: "{{ networktype2 }}"
    vm_hardware:
      memory_mb: "{{ ramvalue }}"
      num_cpus: "{{ cpuvalue }}"
      osid: ubuntu64Guest
      scsi: paravirtual
      vm_cdrom:
        type: "iso"
        iso_path: "DatastoreName/cd-image.iso"
      vm_floppy:
        type: "image"
        image_path: "DatastoreName/floppy-image.flp"
    esxi:
      datacenter: MyDatacenter
      hostname: esx001.mydomain.local
