##
## author: Karol Tomczuk <karol.tomczuk@zerodowntime.pl>
##

---

- name: Install PHP5
  apt:
     name={{ item }}
     state=present
     update_cache=yes
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'
