##
## author: Karol Tomczuk <karol.tomczuk@zerodowntime.pl>
##

---
- name: remove user with sudo privileges
  user:
    name={{ item }}
    state=absent
  with_items: "{{ takesudo_users }}"
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'

- name: add user with regular privileges
  user:
    name={{ item }}
    state=present
    home=/home/{{ item }}
    update_password=on_create
    password=$6$rounds=656000$.25MqRZ2JsYVB/2w$g7YrmTT9.GQu24iSsuG26aSGVjVSgWkvJJUZe0a1Zuq5MR5UBYSz5NMW.U.SCN1KkTZd3v3RstKHbTOiXnayW.
  with_items: "{{ takesudo_users }}"
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'

- name: change ownership of home directory
  file:
    dest=/home/{{ item }}
    owner={{ item }}
    group={{ item }}
    recurse=yes
  with_items: "{{ takesudo_users }}"
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'
