##
## author: Karol Tomczuk <karol.tomczuk@zerodowntime.pl>
##

---
- name: add user with regular privileges
  user:
    name={{ item }}
    state=present
    update_password=on_create
    createhome=yes
    password={{ password }}
  with_items: "{{ regular_users }}"
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'

- name: create .ssh folder for users
  file:
    path=/home/{{ item }}/.ssh state=directory
    owner={{ item }}
    group={{ item }}
  with_items: "{{ regular_users }}"
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'

- name: copy key files to remote host
  copy:
    src=keys/{{ item }}.key
    dest=/home/{{ item }}/.ssh/authorized_keys
    owner={{ item }}
    group={{ item }}
    mode=0600
  with_items: "{{ regular_users }}"
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'

- name: promote user to sudo
  user:
    name={{ item }}
    state=present
    groups=sudo
  with_items: "{{ sudo_users }}"
  when:
    ansible_os_family == 'Ubuntu' or
    ansible_os_family == 'Debian'
