##
## author: Karol Tomczuk <karol.tomczuk@zerodowntime.pl>
##

---
- name: remove regular user
  user:
    name={{ item }}
    state=absent
    move_home=yes
    home=/dev/null
  with_items: "{{ remove_users }}"
  when:
    ansible_distribution == 'Ubuntu' and
    ansible_distribution_release == 'trusty'
